export const orcaleDeck = [
  { nom: "Le Bateleur", displayed: true },
  { nom: "La Papesse", displayed: true },
  { nom: "L'Impératrice", displayed: true },
  { nom: "L'Empereur", displayed: true },
  { nom: "Le Pape", displayed: true },
  { nom: "L'Amoureux", displayed: true },
  { nom: "Le Chariot", displayed: true },
  { nom: "La Justice", displayed: true },
  { nom: "L'Hermite", displayed: true },
  { nom: "La Roue de Fortune", displayed: true },
  { nom: "La Force", displayed: true },
  { nom: "Le Pendu", displayed: true },
  { nom: "L'Arcane sans nom", displayed: true },
  { nom: "La Mort", displayed: true },
  { nom: "La Tempérance", displayed: true },
  { nom: "Le Diable", displayed: true },
  { nom: "La Maison-Dieu", displayed: true },
  { nom: "L'Etoile", displayed: true },
  { nom: "La Lune", displayed: true },
  { nom: "Le Soleil", displayed: true },
  { nom: "Le Jugement", displayed: true },
  { nom: "Le Monde", displayed: true },
];
